const {sql,current,init,hash,json}=require('./_auth');const crypto=require('node:crypto');
module.exports=async(req,res)=>{try{const admin=await current(req);if(!admin||admin.role!=='admin')return json(res,403,{error:'僅限管理員'});await init();
if(req.method==='GET'){const missing=await sql`SELECT id FROM wanglin_users WHERE role='student' AND access_key IS NULL`;for(const u of missing){const key=crypto.randomBytes(32).toString('hex');await sql`UPDATE wanglin_users SET access_key=${key} WHERE id=${u.id} AND access_key IS NULL`}const rows=await sql`SELECT id,email,role,duration_days,first_login_at,expires_at,disabled,created_at,access_key,group_id FROM wanglin_users WHERE role='student' ORDER BY created_at DESC`;const groups=await sql`SELECT id,name,access_key FROM wanglin_groups ORDER BY id DESC`;return json(res,200,{students:rows,groups})}
if(req.method!=='POST')return json(res,405,{error:'不支援此操作'});
const b=req.body||{},action=String(b.action||''),id=String(b.id||''),email=String(b.email||'').trim().toLowerCase(),days=Number(b.days),password=String(b.password||'');
if(action==='create_group'){const name=String(b.name||'').trim().slice(0,100),emails=String(b.emails||'').toLowerCase().split(/[\s,;，；]+/).filter(Boolean);if(!name||emails.length<1||emails.length>200||new Set(emails).size!==emails.length||emails.some(x=>! /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(x))||!Number.isInteger(days)||days<1||days>365)return json(res,400,{error:'請填班別、有效 Email 名單及使用天數（最多 200 人）'});const existing=await sql`SELECT email FROM wanglin_users WHERE email=ANY(${emails})`;if(existing.length)return json(res,409,{error:'已有學員 Email 存在，請先處理重複名單：'+existing.map(x=>x.email).join('、')});const key=crypto.randomBytes(32).toString('hex');const groups=await sql`INSERT INTO wanglin_groups(name,access_key) VALUES(${name},${key}) RETURNING id`;for(const address of emails){const h=hash(crypto.randomBytes(32).toString('hex')),personal=crypto.randomBytes(32).toString('hex');await sql`INSERT INTO wanglin_users(email,password_hash,duration_days,access_key,group_id) VALUES(${address},${h},${days},${personal},${groups[0].id})`}return json(res,200,{ok:true,count:emails.length})}
if(action==='create'){if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||password.length>256||!Number.isInteger(days)||days<1||days>365)return json(res,400,{error:'請填正確 Email 及 1–365 天期限'});
const h=hash(crypto.randomBytes(32).toString('hex')),key=crypto.randomBytes(32).toString('hex');await sql`INSERT INTO wanglin_users(email,password_hash,duration_days,access_key) VALUES(${email},${h},${days},${key})`;return json(res,200,{ok:true})}
if(!/^\d+$/.test(id))return json(res,400,{error:'學員資料錯誤'});
if(action==='delete'){await sql`DELETE FROM wanglin_users WHERE id=${id} AND role='student'`}
else if(action==='regenerate'){const key=crypto.randomBytes(32).toString('hex');await sql`UPDATE wanglin_users SET access_key=${key} WHERE id=${id} AND role='student'`}
else if(action==='disable'){await sql`UPDATE wanglin_users SET disabled=${Boolean(b.disabled)} WHERE id=${id} AND role='student'`}
else if(action==='extend'){if(!Number.isInteger(days)||days<1||days>365)return json(res,400,{error:'天數必須為 1–365'});await sql`UPDATE wanglin_users SET duration_days=duration_days+${days},expires_at=CASE WHEN first_login_at IS NULL THEN NULL ELSE GREATEST(COALESCE(expires_at,NOW()),NOW())+${days}*INTERVAL '1 day' END WHERE id=${id} AND role='student'`}
else if(action==='password'){if(password.length<8||password.length>256)return json(res,400,{error:'密碼至少 8 字'});const h=hash(password);await sql`UPDATE wanglin_users SET password_hash=${h} WHERE id=${id} AND role='student'`}
else return json(res,400,{error:'未知操作'});
return json(res,200,{ok:true});
}catch(e){if(e.code==='23505')return json(res,409,{error:'Email 已經存在'});return json(res,500,{error:'管理操作失敗'})}};